apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: dbz-connect
  annotations:
    strimzi.io/use-connector-resources: "true" 
spec:
  replicas: 1
  version: 3.3.1
  build: 
    output: 
      type: imagestream  
      image: dbz-connect-is:latest
    plugins:
      - name: confluentinc-kafka-connect-jdbc
        artifacts:
          - type: zip
            url: https://d1i4a15mxbxib1.cloudfront.net/api/plugins/confluentinc/kafka-connect-jdbc/versions/10.7.3/confluentinc-kafka-connect-jdbc-10.7.3.zip
      - name: debezium-connector-mysql
        artifacts:
          - type: zip 
            url: https://maven.repository.redhat.com/ga/io/debezium/debezium-connector-mysql/2.1.4.Final-redhat-00001/debezium-connector-mysql-2.1.4.Final-redhat-00001-plugin.zip
      - name: debezium-connector-jdbc
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-jdbc/2.3.1.Final/debezium-connector-jdbc-2.3.1.Final-plugin.tar.gz
  bootstrapServers: amq-kafka-bootstrap:9092