apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: jdbc-sink-connect-mysql
  annotations:
    strimzi.io/use-connector-resources: "true" 
spec:
  config:
    plugin.path: /opt/kafka/plugins/debezium-connector-jdbc/b445ae47/debezium-connector-jdbc
  replicas: 1
  version: 3.4.0
  build: 
    output: 
      type: imagestream  
      image: jdbc-sink-connect-mysql-3-is:latest
    plugins: 
      - name: debezium-connector-jdbc
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-jdbc/2.3.1.Final/debezium-connector-jdbc-2.3.1.Final-plugin.tar.gz
  bootstrapServers: amq-kafka-bootstrap:9092
